### ISSUE TITLE
brainchop.org unreachable

### ISSUE THREAD

**Issue by dkp** [Entodi/MeshNet#1]
Hi,  
Not only is brainchop.org unreachable, but a message to afedorov@mrn.org bounces.

Thanks,

Dianne Patterson

**Comment by Entodi** [comment]
Hello, Dianne Patterson

Sorry, I haven't updated the readme. Brainchop.org is currently not available since our part of the lab moved to a new lab. I have code available in PyTorch and Lua Torch. Let me know how I can help you. Also you can send an email to afedorov@gatech.edu. 

Regards,
Alex

**Comment by dkp** [comment]
Thanks,  I was mostly just curious.  Do you intend to reinstate the web tool?  It sounds really interesting.

**Comment by Entodi** [comment]
Yes, we are planning, but it will take some time since the infrastructure is changed.

**Comment by Entodi** [comment]
@dkp http://brainchop.org/ is up

**Comment by dkp** [comment]
thanks!
